AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 150

Style/BlockDelimiters:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5